name: security
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  process_run: ^0.12.3+1
  shelf: ^1.2.0
  shelf_router: ^1.0.0
  shelf_static: ^1.0.0

dev_dependencies:
  http: ^0.13.0
  lints: ^1.0.1
  test: ^1.15.0
  test_process: ^2.0.0
